### ISSUE TITLE
My Anti-Virus doesn't let me download the scr file

### ISSUE THREAD

**Issue by Adiveler** [BlueJay113/windrift#1]
When trying to download the scr file, my Anti-Virus: Eset Nod32, immediately detain it!

**Comment by y2k04** [comment]
That's odd lol. Feel free to scan it on [VirusTotal](https://www.virustotal.com). If your antivirus tells you it has quarantined the file, you should be able to exclude it from scans in the files OR look in the Quarantined Files tab in your antivirus or Security History.
