### ISSUE TITLE
Does not activate on all screens.

### ISSUE THREAD

**Issue by Mailootje** [BlueJay113/windrift#3]
This .scr is only active on my middle display and does not play on my other screens. I have 3 screens and it does not work for all at the same time as the original windows screen savers.

**Comment by y2k04** [comment]
I'm not sure how to fix this because I am not the owner of the VideoScreensaver program. The code itself doesn't make sense either. It just seems like it is missing some code or something.

Here is the repo: https://sourceforge.net/projects/videosaver/
