### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Dantasstic** [BlueJay113/windrift#5]
Screensaver simply never starts after the set amount of time on Windows 11. All the default screensavers start, but this one will not.

**Comment by y2k04** [comment]
How long do you have it set to?

**Comment by Dantasstic** [comment]
Testing it with 1 minute, but it doesn't work on any amount of time that I have seen.

**Comment by y2k04** [comment]
Have you selected the video to play as a screen saver? (By pressing the settings button)

**Comment by Dantasstic** [comment]
Yes, I followed your instructions exactly. The screensaver will play after installing and selecting the video by running the scr file, and the preview will work as well in the screensaver settings, but it will not start after a time period as it should once applied.

**Comment by y2k04** [comment]
See if this helps: https://www.makeuseof.com/ways-to-fix-malfunctioning-screensaver-windows-10/

**Comment by Dantasstic** [comment]
As I said, all the built in screensavers activate properly. It is simply this one that does not.

**Comment by y2k04** [comment]
Have you tried redownloading the scr file?

**Comment by Dantasstic** [comment]
Good call, that did it :)
