### ISSUE TITLE
win 10 64b - does not work

### ISSUE THREAD

**Issue by biscuit808** [BlueJay113/windrift#6]
Unfortunately, I can't get it to run on my computer. The screen stays black. the standalone mp4 file plays normally for me (using mpc-be). windows savers work, both in preview and after time-out.
![ss](https://user-images.githubusercontent.com/106825750/171881884-e01b2730-e9e7-4157-962c-8b5f3e07276f.png)

**Comment by y2k04** [comment]
Have you tried choosing the video after pressing the Settings button? (the button called Nastaveni`...)

**Comment by biscuit808** [comment]
Hi! Thank you for your reply. Yes, of course. It'll give me the path to the video file. But nothing happens after selecting the video - when I click on the preview, I just get a black screen, just like when the screensaver starts itself after a interval.

**Comment by y2k04** [comment]
Have you tried redownloading the video?

**Comment by biscuit808** [comment]
No, but as i wrote before>  the standalone mp4 file plays normally for me (using mpc-be)

**Comment by y2k04** [comment]
I'm unsure how to fix this. Sorry!
