### ISSUE TITLE
Raised blacks

### ISSUE THREAD

**Issue by gabrielpc4** [BlueJay113/windrift#7]
I noticed when I use the Drift wallpaper as a screen saver, the blacks of the video are not trully black anymore, they are grey-ish.
This is very noticable on my OLED TV and it doesn't happen when I open the video using VLC.
I even tried to render a plain black video using the h264 codec but got the same result.
Anyone facing this issue?

**Comment by y2k04** [comment]
That is just a result of whoever recorded the screensaver. When I am not busy with Year 12, I will get around to figuring out how to make a native version of the screensaver instead of using a crap video downloaded from YouTube.

**Comment by sandydoo** [comment]
> I will get around to figuring out how to make a native version of the screensaver

@y2k04, https://github.com/sandydoo/flux 😉

**Comment by y2k04** [comment]
Yay!! Thank you for sending that to me, I shall now archive this repo :))

> > I will get around to figuring out how to make a native version of the screensaver
> 
> @y2k04, https://github.com/sandydoo/flux 😉
